[package]
name = "monitor_detect"
version = "0.1.0"
edition = "2021"
publish = ["artifactory"]

[dependencies]

[dependencies.winapi]
version = "0.3.9"
# Include functionality defined in winuser.h.
features = ["winuser"]
